### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by Hisamera** [shuaimu/borrow-cpp#1]
First things first, as you have no license it's automatically "All rights reserved" I don't know if you knew that, so no one can use your code in theirs projects (at least officialy).

Second, maybe you want some help? I was recently employed at a coding company so this would help me greatly to hone my skills faster, plus I'm not deluding myself that I don't make stupid mistakes, so this would be a great tool as I know what it feels like to program in Rust and having everything magically work. 

But you would need to sort licensing issue first. Infer is under MIT License, so you could use that, or something else, but your code, your choice. Also in readme there should be something like "Any contribution intentionally submitted for inclusion in the work by you, as defined in the {Name of the license here] license, shall be licensed as above, without any additional terms or conditions." So there won't be any legal problems in the future.

I'll appreciate any response :)

**Comment by shuaimu** [comment]
license added; help/feedback are welcome.
